add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$character"""

[directory]
style = "bold #89b4fa"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold #a6e3a1"

[git_status]
style = "bold #f38ba8"

[nodejs]
symbol = " "
style = "bold #a6e3a1"
format = "[$symbol($version )]($style)"

[character]
success_symbol = "[❯](bold #89b4fa)"
error_symbol = "[❯](bold #f38ba8)"
